#! /usr/bin/env node

console.log(
    "This script populates some test machines to your database."
  );
  // importation des modèles
  const sequelize = require("./db");
  const { User, Role, Permission } = require("./User");
  const Region = require("./region");
  const Commune = require("./commune");
  const Adresse = require("./adresse");
  const Publication = require("./publication");
  const Parking = require("./parking");
  const Place = require("./place");
  const TypeVehicule = require("./typeVehicule");
  const Tarif = require("./tarif");
  const Vehicule = require('./vehicule');
  const Reservation = require("./reservation");
  const Trafic = require("./trafic");
  const Location = require("./location");
  const PlageHoraire = require("./plageHoraire");
  
  const bcrypt = require("bcrypt");
  
  const saltRounds = 10;
  
  (async () => {
    await sequelize.sync({force: true});
  // creation des differentes permissions
    const [
      createPlacePerm,
      editPlacePerm,
      deletePlacePerm,
      listPlacesPerm,
      viewPlaceDetailsPerm,
      createParkingPerm,
      editParkingPerm,
      deleteParkingPerm,
      listParkingsPerm,
      viewParkingDetailsPerm,
      createReservationPerm,
      editReservationPerm,
      deleteReservationPerm,
      listReservationsPerm,
      viewReservationDetailsPerm,
      createRegionPerm,
      editRegionPerm,
      deleteRegionPerm,
      listRegionsPerm,
      viewRegionDetailsPerm,
      createCommunePerm,
      editCommunePerm,
      deleteCommunePerm,
      listCommunesPerm,
      viewCommuneDetailsPerm,
      createAdressePerm,
      editAdressePerm,
      deleteAdressePerm,
      listAdressesPerm,
      viewAdresseDetailsPerm,
      createPlageHorairePerm,
      editPlageHorairePerm,
      deletePlageHorairePerm,
      listPlageHorairesPerm,
      viewPlageHoraireDetailsPerm,
      createTraficPerm,
      editTraficPerm,
      deleteTraficPerm,
      listTraficsPerm,
      viewTraficDetailsPerm,
      createTarifPerm,
      editTarifPerm,
      deleteTarifPerm,
      listTarifsPerm,
      viewTarifDetailsPerm,
      createVehiculePerm,
      editVehiculePerm,
      deleteVehiculePerm,
      listVehiculesPerm,
      viewVehiculeDetailsPerm,
      createPublicationPerm,
      editPublicationPerm,
      deletePublicationPerm,
      listPublicationsPerm,
      viewPublicationDetailsPerm,
      createTypeVehiculePerm,
      editTypeVehiculePerm,
      deleteTypeVehiculePerm,
      listTypeVehiculesPerm,
      viewTypeVehiculeDetailsPerm,
      createLocationPerm,
      editLocationPerm,
      deleteLocationPerm,
      listLocationsPerm,
      viewLocationDetailsPerm,
      createRolePerm,
      editRolePerm,
      deleteRolePerm,
      listRolesPerm,
      viewRoleDetailsPerm,
    ] = await Permission.bulkCreate([
      { name: "createPlace" },
      { name: "editPlace" },
      { name: "deletePlace" },
      { name: "listPlaces" },
      { name: "viewPlaceDetails" },
      { name: "createParking" },
      { name: "editParking" },
      { name: "deleteParking" },
      { name: "listParkings" },
      { name: "viewParkingDetails"},
      { name: "createReservation" },
      { name: "editReservation" },
      { name: "deleteReservation" },
      { name: "listReservations" },
      { name: "viewReservationDetails"},
      { name: "createRegion" },
      { name: "editRegion" },
      { name: "deleteRegion" },
      { name: "listRegions" },
      { name: "viewRegionDetails"},
      { name: "createCommune" },
      { name: "editCommune" },
      { name: "deleteCommune" },
      { name: "listCommunes" },
      { name: "viewCommuneDetails"},
      { name: "createAdresse" },
      { name: "editAdresse" },
      { name: "deleteAdresse" },
      { name: "listAdresses" },
      { name: "viewAdresseDetails"},
      { name: "createPlageHoraire" },
      { name: "editPlageHoraire" },
      { name: "deletePlageHoraire" },
      { name: "listPlageHoraires" },
      { name: "viewPlageHoraireDetails"},
      { name: "createTrafic" },
      { name: "editTrafic" },
      { name: "deleteTrafic" },
      { name: "listTrafics" },
      { name: "viewTraficDetails"},
      { name: "createTarif" },
      { name: "editTarif" },
      { name: "deleteTarif" },
      { name: "listTarifs" },
      { name: "viewTarifDetails"},
      { name: "createVehicule"},
      { name: "editVehicule"},
      { name: "deleteVehicule"},
      { name: "listVehicules"},
      { name: "viewVehiculeDetails"},
      { name: "createPublication"},
      { name: "editPublication"},
      { name: "deletePublication"},
      { name: "listPublications"},
      { name: "viewPublicationDetails"},
      { name: "createTypeVehicule"},
      { name: "editTypeVehicule"},
      { name: "deleteTypeVehicule"},
      { name: "listTypeVehicules"},
      { name: "viewTypeVehiculeDetails"},
      { name: "createLocation"},
      { name: "editLocation"},
      { name: "deleteLocation"},
      { name: "listLocations"},
      { name: "viewLocationDetails"},
      { name: "createRole"},
      { name: "editRole"},
      { name: "deleteRole"},
      { name: "listRoles"},
      { name: "viewRoleDetails"},
    ]);
    
    const [clientRole, proprietaireRole, managerRole] = await Role.bulkCreate([
      { name: "client" },
      { name: "proprietaire" },
      { name: "manager" },
    ]);
  
    await Promise.all([
      clientRole.addPermissions([
        createPlacePerm,
        editPlacePerm,
        deletePlacePerm,
        listPlacesPerm,
        viewPlaceDetailsPerm,
        createParkingPerm,
        editParkingPerm,
        deleteParkingPerm,
        listParkingsPerm,
        viewParkingDetailsPerm,
        createReservationPerm,
        editReservationPerm,
        deleteReservationPerm,
        listReservationsPerm,
        viewReservationDetailsPerm,
        createRegionPerm,
        editRegionPerm,
        deleteRegionPerm,
        listRegionsPerm,
        viewRegionDetailsPerm,
        createCommunePerm,
        editCommunePerm,
        deleteCommunePerm,
        listCommunesPerm,
        viewCommuneDetailsPerm,
        createAdressePerm,
        editAdressePerm,
        deleteAdressePerm,
        listAdressesPerm,
        viewAdresseDetailsPerm,
        createPlageHorairePerm,
        editPlageHorairePerm,
        deletePlageHorairePerm,
        listPlageHorairesPerm,
        viewPlageHoraireDetailsPerm,
        createTraficPerm,
        editTraficPerm,
        deleteTraficPerm,
        listTraficsPerm,
        viewTraficDetailsPerm,
        createTarifPerm,
        editTarifPerm,
        deleteTarifPerm,
        listTarifsPerm,
        viewTarifDetailsPerm,
        createVehiculePerm,
        editVehiculePerm,
        deleteVehiculePerm,
        listVehiculesPerm,
        viewVehiculeDetailsPerm,
        createPublicationPerm,
        editPublicationPerm,
        deletePublicationPerm,
        listPublicationsPerm,
        viewPublicationDetailsPerm,
        createTypeVehiculePerm,
        editTypeVehiculePerm,
        deleteTypeVehiculePerm,
        listTypeVehiculesPerm,
        viewTypeVehiculeDetailsPerm,
        createLocationPerm,
        editLocationPerm,
        deleteLocationPerm,
        listLocationsPerm,
        viewLocationDetailsPerm,]),
      proprietaireRole.addPermissions([
        createPlacePerm,
        editPlacePerm,
        deletePlacePerm,
        listPlacesPerm,
        viewPlaceDetailsPerm,
        createParkingPerm,
        editParkingPerm,
        deleteParkingPerm,
        listParkingsPerm,
        viewParkingDetailsPerm,
        createReservationPerm,
        editReservationPerm,
        deleteReservationPerm,
        listReservationsPerm,
        viewReservationDetailsPerm,
        createRegionPerm,
        editRegionPerm,
        deleteRegionPerm,
        listRegionsPerm,
        viewRegionDetailsPerm,
        createCommunePerm,
        editCommunePerm,
        deleteCommunePerm,
        listCommunesPerm,
        viewCommuneDetailsPerm,
        createAdressePerm,
        editAdressePerm,
        deleteAdressePerm,
        listAdressesPerm,
        viewAdresseDetailsPerm,
        createPlageHorairePerm,
        editPlageHorairePerm,
        deletePlageHorairePerm,
        listPlageHorairesPerm,
        viewPlageHoraireDetailsPerm,
        createTraficPerm,
        editTraficPerm,
        deleteTraficPerm,
        listTraficsPerm,
        viewTraficDetailsPerm,
        createTarifPerm,
        editTarifPerm,
        deleteTarifPerm,
        listTarifsPerm,
        viewTarifDetailsPerm,
        createVehiculePerm,
        editVehiculePerm,
        deleteVehiculePerm,
        listVehiculesPerm,
        viewVehiculeDetailsPerm,
        createPublicationPerm,
        editPublicationPerm,
        deletePublicationPerm,
        listPublicationsPerm,
        viewPublicationDetailsPerm,
        createTypeVehiculePerm,
        editTypeVehiculePerm,
        deleteTypeVehiculePerm,
        listTypeVehiculesPerm,
        viewTypeVehiculeDetailsPerm,
        createLocationPerm,
        editLocationPerm,
        deleteLocationPerm,
        listLocationsPerm,
        viewLocationDetailsPerm,]),
      managerRole.addPermissions([
        createPlacePerm,
        editPlacePerm,
        deletePlacePerm,
        listPlacesPerm,
        viewPlaceDetailsPerm,
        createParkingPerm,
        editParkingPerm,
        deleteParkingPerm,
        listParkingsPerm,
        viewParkingDetailsPerm,
        createReservationPerm,
        editReservationPerm,
        deleteReservationPerm,
        listReservationsPerm,
        viewReservationDetailsPerm,
        createRegionPerm,
        editRegionPerm,
        deleteRegionPerm,
        listRegionsPerm,
        viewRegionDetailsPerm,
        createCommunePerm,
        editCommunePerm,
        deleteCommunePerm,
        listCommunesPerm,
        viewCommuneDetailsPerm,
        createAdressePerm,
        editAdressePerm,
        deleteAdressePerm,
        listAdressesPerm,
        viewAdresseDetailsPerm,
        createPlageHorairePerm,
        editPlageHorairePerm,
        deletePlageHorairePerm,
        listPlageHorairesPerm,
        viewPlageHoraireDetailsPerm,
        createTraficPerm,
        editTraficPerm,
        deleteTraficPerm,
        listTraficsPerm,
        viewTraficDetailsPerm,
        createTarifPerm,
        editTarifPerm,
        deleteTarifPerm,
        listTarifsPerm,
        viewTarifDetailsPerm,
        createVehiculePerm,
        editVehiculePerm,
        deleteVehiculePerm,
        listVehiculesPerm,
        viewVehiculeDetailsPerm,
        createPublicationPerm,
        editPublicationPerm,
        deletePublicationPerm,
        listPublicationsPerm,
        viewPublicationDetailsPerm,
        createTypeVehiculePerm,
        editTypeVehiculePerm,
        deleteTypeVehiculePerm,
        listTypeVehiculesPerm,
        viewTypeVehiculeDetailsPerm,
        createLocationPerm,
        editLocationPerm,
        deleteLocationPerm,
        listLocationsPerm,
        viewLocationDetailsPerm,
        createRolePerm,
        editRolePerm,
        deleteRolePerm,
        listRolesPerm,
        viewRoleDetailsPerm,]),
    ]);
    //remplissage de la table region
    await Region.bulkCreate([
      { nom: "Région flamande" },
      { nom: "Région de Bruxelles-Capitale" },
      { nom: "Région wallonne" }
    ]);
    //remplissage de la table Commune
    await Commune.bulkCreate([
      //Liste des communes de la région de Bruxelles-Capitale
      { nom:"Anderlecht", codePostal:1070, regionNom:"Région de Bruxelles-Capitale"},
      { nom:"Auderghem", codePostal:1160,regionNom:"Région de Bruxelles-Capitale"},
      { nom:"Berchem-Sainte-Agathe", codePostal:1082,regionNom:"Région de Bruxelles-Capitale"},
      { nom:"Ville de Bruxelles", codePostal:1000,regionNom:"Région de Bruxelles-Capitale"},
      { nom:"Etterbeek", codePostal:1040,regionNom:"Région de Bruxelles-Capitale"},
      { nom:"Evere", codePostal:1140,regionNom:"Région de Bruxelles-Capitale"},
      { nom:"Forest", codePostal:1190,regionNom:"Région de Bruxelles-Capitale"},
      { nom:"Ganshoren", codePostal:1083,regionNom:"Région de Bruxelles-Capitale"},
      { nom:"Ixelles", codePostal:1050, regionNom:"Région de Bruxelles-Capitale"},
      { nom:"Jette", codePostal:1090,regionNom:"Région de Bruxelles-Capitale"},
      { nom:"Koekelberg", codePostal:1081, regionNom:"Région de Bruxelles-Capitale"},
      { nom:"Molenbeek-Saint-Jean", codePostal:1080, regionNom:"Région de Bruxelles-Capitale"},
      { nom:"Saint-Gilles", codePostal:1060,regionNom:"Région de Bruxelles-Capitale"},
      { nom:"Saint-Josse-ten-Noode", codePostal:1210, regionNom:"Région de Bruxelles-Capitale"},
      { nom:"Schaerbeek", codePostal:1030,regionNom:"Région de Bruxelles-Capitale"},
      { nom:"Uccle", codePostal:1180, regionNom:"Région de Bruxelles-Capitale"},
      //Liste des communes de la Région flamande
      { nom:"Aalter", codePostal:9880, regionNom:"Région flamande"},
      { nom:"Aerschot", codePostal:3200, regionNom:"Région flamande"},
      { nom:"Aartselaar", codePostal:2630, regionNom:"Région flamande"},
      { nom:"Affligem", codePostal:1790, regionNom:"Région flamande"},
      { nom:"Alken", codePostal:3570, regionNom:"Région flamande"},  
      { nom:"AALST", codePostal:9300, regionNom:"Région flamande"},
      { nom:"ALVERINGEM", codePostal:8690, regionNom:"Région flamande"},
      { nom:"ANZEGEM", codePostal:8570, regionNom:"Région flamande"},       
      { nom: "ASSENEDE", codePostal:9960, regionNom:"Région flamande"},
      { nom:"AVELGEM", codePostal:8580, regionNom:"Région flamande"},
      { nom:"BEVEREN-WAAS", codePostal:9120, regionNom:"Région flamande"},
      { nom: "BILZEN", codePostal: 3740, regionNom:"Région flamande" },
      { nom:"BLANKENBERGE", codePostal:8370, regionNom:"Région flamande"},
      { nom: "BOCHOLT", codePostal: 3950, regionNom:"Région flamande" },
      { nom: "BONHEIDEN", codePostal:2820 , regionNom:"Région flamande"},
      { nom:"BRAKEL", codePostal:9660, regionNom:"Région flamande"},
      { nom:"BREDENE", codePostal:8450, regionNom:"Région flamande"},
      { nom:"DAMME", codePostal:8340, regionNom:"Région flamande"},
      { nom:"DEINZE", codePostal:9800, regionNom:"Région flamande"},
      { nom:"DENDERMONDE", codePostal:9200, regionNom:"Région flamande"},
      { nom:"DIKSMUIDE", codePostal:8600, regionNom:"Région flamande"},
      { nom:"ERPE-MERE", codePostal:9420, regionNom:"Région flamande"},
      { nom:"EVERGEM", codePostal:9940, regionNom:"Région flamande"},
      { nom:"GAVERE", codePostal:9890, regionNom:"Région flamande"},
      { nom: "GENT", codePostal: 9000, regionNom:"Région flamande" },
      { nom:"GERAARDSBERGEN", codePostal:9500, regionNom:"Région flamande"},
      { nom:"GISTEL", codePostal:8470, regionNom:"Région flamande"},
      { nom: "HAACHT", codePostal: 3150 , regionNom:"Région flamande"},
      { nom:"HAALTERT", codePostal:9450, regionNom:"Région flamande"},
      { nom:"HERZELE", codePostal:9550, regionNom:"Région flamande"},
      { nom:"HEUVELLAND", codePostal:8950, regionNom:"Région flamande"},
      { nom: "HOESELT", codePostal: 3730 , regionNom:"Région flamande"},
      { nom: "HOOGSTRATEN", codePostal: 2323 , regionNom:"Région flamande"},
      { nom:"HOREBEKE", codePostal:9667, regionNom:"Région flamande"},
      { nom:"HOUTHULST", codePostal:8650, regionNom:"Région flamande"},
      { nom: "HULDENBERG", codePostal: 3040, regionNom:"Région flamande"},
      { nom:"ICHTEGEM", codePostal:8480, regionNom:"Région flamande"},
      { nom:"IEPER", codePostal:8900, regionNom:"Région flamande"},
      { nom:"INGELMUNSTER",codePostal:8770, regionNom:"Région flamande"},
      { nom:"IZEGEM", codePostal:8870, regionNom:"Région flamande"},
      { nom: "JABBEKE",codePostal: 8490, regionNom:"Région flamande"},
      { nom:"KLUISBERGEN", codePostal:9690, regionNom:"Région flamande"},
      { nom:"KNOKKE-HEIST", codePostal:8300, regionNom:"Région flamande"},
      { nom:"KOEKELARE", codePostal:8680, regionNom:"Région flamande"},
      //Liste des communes de la Région wallonne
      { nom:"ASSESSE", codePostal: 5333 , regionNom:"Région wallonne"},
      { nom: "AYWAILLE", codePostal: 4920, regionNom:"Région wallonne" }, 
      { nom:"BELOEIL", codePostal: 7971 , regionNom:"Région wallonne"},
      { nom:"BERNISSART", codePostal: 7322, regionNom:"Région wallonne" }, 
      { nom:"CINEY", codePostal:5590, regionNom:"Région wallonne"},
      { nom: "CLAVIER", codePostal: 4560, regionNom:"Région wallonne" }, 
      { nom: "COLFONTAINE", codePostal: 7340 , regionNom:"Région wallonne"},
    ]);
    //  remplissage de la table adresse
    await Adresse.bulkCreate([
      { nom: "rue de la victoire", numero: 200, communeId:9},
      { nom: "impasse de picardie", numero: 3, communeId:3},
      { nom: "Rue de l'Abattoir", numero: 200, communeId:1},
      { nom: "Rue Brederode", numero: 16, communeId:19},
      { nom: "Rue Haute", numero: 298, communeId:52},
      { nom: "Rue Royale", numero: 120, communeId:32},
      { nom: "Rue du Lombard ", numero: 69, communeId:10},
      { nom: "Rue Royale", numero: 76, communeId:17},
      { nom: "rue Jospeh Schmidt", numero: 34, communeId:51},
      { nom: "rue félix martin", numero: 10, communeId:41},
      { nom: "Rue Victor Gilmet", numero: 12, communeId:16},
      { nom: "Rue des Sarpettes", numero: 11, communeId:11},
      { nom: "Chemin du fond des coupes", numero: 23, communeId:21},
      { nom: "Leurshoek", numero: 96, communeId:31},
      { nom: "Leurshoek", numero: 67, communeId:32},
      { nom: "Schaarbeekstraat", numero: 23, communeId:66},
    ]);
  //création des mots de passe
    const verlyPasswordHash = await bcrypt.hash("kouwe", saltRounds);
    const parfaitPasswordHash = await bcrypt.hash("Parfait password", saltRounds);
    const mariePasswordHash = await bcrypt.hash("Marie password", saltRounds);
    const andrePasswordHash = await bcrypt.hash("Andre password", saltRounds);
    const samuelPasswordHash = await bcrypt.hash("Samuel password", saltRounds);
    const fredPasswordHash = await bcrypt.hash("Fred password", saltRounds);
    const arthurPasswordHash = await bcrypt.hash("Arthur password", saltRounds);
    const louisPasswordHash = await bcrypt.hash("Louis password", saltRounds);
    const ronPasswordHash = await bcrypt.hash("Ron password", saltRounds);
    const tantyPasswordHash = await bcrypt.hash("Tanty password", saltRounds);
    const romualdPasswordHash = await bcrypt.hash("Romuald password", saltRounds);
    const elodiePasswordHash = await bcrypt.hash("Elodie password", saltRounds);
    const abdouPasswordHash = await bcrypt.hash("Abdou password", saltRounds);
    const remyPasswordHash = await bcrypt.hash("Remy password", saltRounds);
    const veroPasswordHash = await bcrypt.hash("Vero password", saltRounds);
    const christinePasswordHash = await bcrypt.hash("Christine password", saltRounds);
    const françoisPasswordHash = await bcrypt.hash("François password", saltRounds);
    const manouPasswordHash = await bcrypt.hash("Manou password", saltRounds);
    const rachelPasswordHash = await bcrypt.hash("Rachel password", saltRounds);
    const olgaPasswordHash = await bcrypt.hash("Olga password", saltRounds);
  
    const [ verly, parfait, marie, andre, samuel, fred, arthur, louis, ron, tanty, romuald, elodie,
      abdou, remy, vero, christine, françois, manou, rachel, olga  ] = await User.bulkCreate([
        {   
            username: "verly",
            passwordHash: verlyPasswordHash,
            usermail: "verly@gmail.com",
            nom: "verlaine",
            prenom: "verly",
            telephone: "0487 25 63 41",
            adresseId:4,
        },
        { 
          username: "parfait",
          passwordHash: parfaitPasswordHash,
          usermail: "parfait@yopmail.com",
          nom: "bougong",
          prenom: "parfait",
          telephone: "0489 25 73 41",
          adresseId:3,
        },
        { 
          username: "marie",
          passwordHash: mariePasswordHash,
          usermail: "marie@yopmail.com",
          nom: "marie",
          prenom: "jean",
          telephone: "0488 25 69 11",
          adresseId:2,
        },
        { 
          username: "andre",
          passwordHash: andrePasswordHash,
          usermail: "andre@yopmail.com",
          nom: "andre",
          prenom: "roland",
          telephone: "0468 27 69 11",
          adresseId:1,
        }, 
        { 
          username: "samuel",
          passwordHash: samuelPasswordHash,
          usermail: "samuel@yopmail.com",
          nom: "samuel",
          prenom: "joseph",
          telephone: "0477 97 69 01",
          adresseId:16,
        },
        { 
          username: "fred",
          passwordHash: fredPasswordHash,
          usermail: "fred@yopmail.com",
          nom: "fred",
          prenom: "paul",
          telephone: "0474 01 20 01",
          adresseId:15,
        },
        { 
          username: "arthur",
          passwordHash: arthurPasswordHash,
          usermail: "arthur@yopmail.com",
          nom: "arthur",
          prenom: "gérome",
          telephone: "0475 41 21 91",
          adresseId:14,
        },
        { 
          username: "louis",
          passwordHash: louisPasswordHash,
          usermail: "louis@yopmail.com",
          nom: "louis",
          prenom: "sylvain",
          telephone: "0487 50 41 61",
          adresseId:13,
        },
        { 
          username: "ron",
          passwordHash: ronPasswordHash,
          usermail: "ron@yopmail.com",
          nom: "ron",
          prenom: "yves",
          telephone: "0486 65 61 32",
          adresseId:12,
        },
        {  
          username: "tanty",
          passwordHash: tantyPasswordHash,
          usermail: "tanty@yopmail.com",
          nom: "annette",
          prenom: "tanty",
          telephone: "0465 23 20 10",
          adresseId:11,
        },
        { 
          username: "romuald",
          passwordHash: romualdPasswordHash,
          usermail: "romuald@yopmail.com",
          nom: "daubel",
          prenom: "romuald",
          telephone: "0489 74 52 03",
          adresseId:10,
        },
        { 
          username: "elodie",
          passwordHash: elodiePasswordHash,
          usermail: "elodie@yopmail.com",
          nom: "blanchard",
          prenom: "elodie",
          telephone: "0488 17 22 63",
          adresseId:9,
        },
        { 
          username: "abdou",
          passwordHash: abdouPasswordHash,
          usermail: "abdou@yopmail.com",
          nom: "el-khatabi",
          prenom: "abdou",
          telephone: "0470 09 99 99",
          adresseId:8,
        },
        { 
          username: "remy",
          passwordHash: remyPasswordHash,
          usermail: "remy@yopmail.com",
          nom: "bernard",
          prenom: "remy",
          telephone: "0466 52 11 02",
          adresseId:7,
        },
        { 
          username: "vero",
          passwordHash: veroPasswordHash,
          usermail: "vero@yopmail.com",
          nom: "cathérine",
          prenom: "vero",
          telephone: "0476 00 14 41",
          adresseId:6,
        },
        { 
          username: "christine",
          passwordHash: christinePasswordHash,
          usermail: "christine@yopmail.com",
          nom: "blanche",
          prenom: "christine",
          telephone: "0478 97 88 47",
          adresseId:5,
        },
        { 
          username: "françois",
          passwordHash: françoisPasswordHash,
          usermail: "françois@yopmail.com",
          nom: "dumoulin",
          prenom: "françois",
          telephone: "0465 96 65 56",
          adresseId:4,
        },
        { 
          username: "manou",
          passwordHash: manouPasswordHash,
          usermail: "manou@yopmail.com",
          nom: "vanmeren",
          prenom: "manou",
          telephone: "0490 56 74 25",
          adresseId:3,
        },
        { 
          username: "rachel",
          passwordHash: rachelPasswordHash,
          usermail: "rachel@yopmail.com",
          nom: "léa",
          prenom: "rachel",
          telephone: "0471 54 12 96",
          adresseId:2,
        },
        { 
          username: "olga",
          passwordHash: olgaPasswordHash,
          usermail: "olga@yopmail.com",
          nom: "arnica",
          prenom: "olga",
          telephone: "0473 20 02 03",
          adresseId:1,
        },
    ]);
    // attribution des role aux utilisateurs
    await Promise.all([
      verly.setRoles([managerRole]),
        parfait.setRoles([clientRole]),
        marie.setRoles([clientRole]),
        andre.setRoles([proprietaireRole]),
        samuel.setRoles([clientRole]),
        fred.setRoles([clientRole]),
        arthur.setRoles([proprietaireRole]),
        louis.setRoles([clientRole]),
        ron.setRoles([clientRole]),
        tanty.setRoles([proprietaireRole]),
        romuald.setRoles([clientRole]),
        elodie.setRoles([proprietaireRole]),
        abdou.setRoles([clientRole]),
        remy.setRoles([proprietaireRole]),
        vero.setRoles([proprietaireRole]),
        christine.setRoles([proprietaireRole]),
        françois.setRoles([clientRole]),
        manou.setRoles([clientRole]),
        rachel.setRoles([clientRole]),
        olga.setRoles([proprietaireRole])
    ]);
  //remplissage de la table publication
  await Publication.bulkCreate([
    { description: ["Bonjour, je mets à votre disposition ma place qui est située sur le trottoir" ],
      userUsername:"verly",
    },
    { description: ["Bonjour, je mets à votre disposition ma place un parking privé" ],
      userUsername:"elodie",
    },
    { description: ["Bonjour, je mets à votre disposition ma place dans box de garage" +
    ", avec camera de surveillance 24h/24" ],
      userUsername:"andre",
    },
    { description: ["Bonjour, je mets à votre disposition plusieurs places dans" +
    "dans le parking de mon immeuble" ],
      userUsername:"arthur",
    },
    { description: ["Bonjour, je mets à votre disposition ma place qui est située dans" +
    " le centre de la ville" ],
      userUsername:"olga",
    },
  ]);
  //remplissage de la table parking
await Parking.bulkCreate([
  {
    nombrePlaces: 1,
    userUsername:"elodie",
    adresseId: 1,
  },
  {
    nombrePlaces: 2,
    userUsername:"arthur",
    adresseId: 2,
  },
  {
    nombrePlaces: 9,
    userUsername:"andre",
    adresseId: 3,
  },
  {
    nombrePlaces: 4,
    userUsername:"olga",
    adresseId: 4,
  },
  {
    nombrePlaces: 3,
    userUsername:"elodie",
    adresseId: 5,
    
  },
  {
    nombrePlaces: 5,
    userUsername:"remy",
    adresseId: 10,
  },
  {
    nombrePlaces:6,
    userUsername:"tanty",
    adresseId: 6,
  },
  {
    nombrePlaces: 7,
    userUsername:"vero",
    adresseId: 7,
  },
  {
    nombrePlaces: 8,
    userUsername:"vero",
    adresseId:8,
  },
  {
    nombrePlaces: 10,
    userUsername:"remy",
    adresseId: 9,
  },
  {
    nombrePlaces: 14,
    userUsername:"tanty",
    adresseId: 10,
  },
  {
    nombrePlaces: 24,
    userUsername:"olga",
    adresseId: 11,
  },
  {
    nombrePlaces: 10,
    userUsername:"elodie",
    adresseId: 12,
  },
  {
    nombrePlaces: 24,
    userUsername:"christine",
    adresseId:13 ,
  },
  {
    nombrePlaces: 19,
    userUsername:"arthur",
    adresseId:14,
  },
  {
    nombrePlaces: 20,
    userUsername:"andre",
    adresseId: 16,
  },
  ]);
  // remplissage de la table place
const [a, b, c, d, e, f, g, h, i, j, k, l] = await Place.bulkCreate([
  {
      description: "aller chez l'habitant",
      dimension: "300 x 200",    
      parkingId:12,   
    },
  {
    description: "présence d'un box-garage",
    dimension: "1300 x 752",
    parkingId:11,
  
  },
  {
    description: "présence de caméra de surveillance",
    dimension: "300 x 200",
    parkingId:10,
    
  },
  {
    description: "place disponible sur le trottoir",
    dimension: "300 x 450",
    parkingId:9,

  },
  {
    description: "aller chez l'habitant",
    dimension: "400 x 230",
    parkingId:8,
  
  },
  {
      description: "aller chez l'habitant",
      dimension: "400 x 300",
      parkingId:7,
      managerOnly: true,
  },
  {
      description: "aller chez l'habitant",
      dimension: "500 x 300",
      parkingId:6,
      managerOnly: true,
  },
  {
      description: "aller chez l'habitant",
      dimension: "400 x 300",
      parkingId:5,
      managerOnly: true,
  },
  {
      description: "place de parking devant ma maison sur la route principale",
      dimension: "600 x 400",
      parkingId:4,
  },
  {
      description: "place de parking dans la rue",
      dimension: "1000 x 400",
      parkingId:3,
  },
  {
      description: "parking dans mon garage",
      dimension: "450 340",
      parkingId:2,
  },
  {
      description: "rue devant le domicile de ma maison",
      dimension: "561 x 300",
      parkingId:1,
  },
]);
  //remplissage de la table typeVehicule
  const [quatreTypeVehicule, berlinesTypeVehicule, breakTypeVehicule,
        monospaceTypeVehicule, citadinesTypeVehicule, cabrioletsTypeVehicule, 
        pickupsTypeVehicule, crossoversTypeVehicule, fourgonTypeVehicule,]
  = await TypeVehicule.bulkCreate([
    { nom: "4x4"},
    { nom: "auto berlines"},
    { nom: "automobiles Break"},
    { nom: "voitures monospace"},
    { nom: "citadines"},
    { nom: "cabriolets et coupé"},
    { nom: "Pick ups"},
    { nom: "crossovers"},
    { nom: "utilitaires et fourgonnette"},
  ]);
  //attribution du type de véhicule au places de parking
  await Promise.all([
    a.setTypeVehicules([quatreTypeVehicule]),
    b.setTypeVehicules([berlinesTypeVehicule]),
    c.setTypeVehicules([breakTypeVehicule]),
    d.setTypeVehicules([monospaceTypeVehicule]),
    e.setTypeVehicules([citadinesTypeVehicule]),
    f.setTypeVehicules([cabrioletsTypeVehicule]),
    g.setTypeVehicules([pickupsTypeVehicule]),
    h.setTypeVehicules([crossoversTypeVehicule]),
    i.setTypeVehicules([fourgonTypeVehicule]),
    j.setTypeVehicules([crossoversTypeVehicule]),
    k.setTypeVehicules([pickupsTypeVehicule]),
    l.setTypeVehicules([quatreTypeVehicule]),
  ]);
  
  //Remplissage table plageHoraire
   await PlageHoraire.bulkCreate([
    { heureDebut: '09:02', heureFin: '10:03'},
   ]);
  await Trafic.bulkCreate([
    {nom: "haut", plageHoraireId:1},
    {nom: "bas", plageHoraireId:1},
  ]);
  //remplissage de la table tarif
  await Tarif.bulkCreate([
    { montant: 0.06, typeVehiculeId:2, parkingId:1, traficId:1},
    { montant: 0.02, typeVehiculeId:1, parkingId:2, traficId:1},
    { montant: 0.03, typeVehiculeId:3, parkingId:3, traficId:1},
    { montant: 0.01, typeVehiculeId:4, parkingId:4, traficId:1},
    { montant: 0.08, typeVehiculeId:5, parkingId:5, traficId:1},
    { montant: 0.20, typeVehiculeId:6, parkingId:6, traficId:2},
    { montant: 0.30, typeVehiculeId:7, parkingId:7, traficId:1},
    { montant: 0.07, typeVehiculeId:8, parkingId:8, traficId:1},
    { montant: 0.05, typeVehiculeId:9, parkingId:9, traficId:1},
    { montant: 0.09, typeVehiculeId:1, parkingId:10, traficId:1},
    { montant: 0.03, typeVehiculeId:2, parkingId:11, traficId:1},
    { montant: 0.05, typeVehiculeId:3, parkingId:12, traficId:1},
    { montant: 0.10, typeVehiculeId:4, parkingId:13, traficId:1},
    { montant: 0.06, typeVehiculeId:5, parkingId:14, traficId:1},
  ]);
  //remplissage de la table vehicule
 await Vehicule.bulkCreate([
  { numero_immatriculation: "1-ZAB-003", typeVehiculeId:1},
  { numero_immatriculation: "1-ABC-003", typeVehiculeId:2},
  { numero_immatriculation: "T-XAA-001", typeVehiculeId:3},
  { numero_immatriculation: "T-LAA-001", typeVehiculeId:4},
  { numero_immatriculation: "O-AAA-001", typeVehiculeId:5},
  { numero_immatriculation: "Q-AAA-001", typeVehiculeId:6},
  { numero_immatriculation: "1-BYK-297", typeVehiculeId:7},
  { numero_immatriculation: "9-ZZZ-999", typeVehiculeId:8},
  { numero_immatriculation: "1-JCV-007", typeVehiculeId:9},
  { numero_immatriculation: "2-AAA-001", typeVehiculeId:1},
  { numero_immatriculation: "T-LAA-012", typeVehiculeId:2},
  { numero_immatriculation: "T-XAA-001", typeVehiculeId:3},
  { numero_immatriculation: "M-AAA-001", typeVehiculeId:4},
  { numero_immatriculation: "1-AKC-123", typeVehiculeId:5},
  { numero_immatriculation: "M-AAA-051", typeVehiculeId:6},
]);
  //remplissage de la table reservation
  await Reservation.bulkCreate([
    {
    codeReservation: "2021-02-01T08:00:00.000Z",
    dateReservation: '2021-02-20',
    dateOccupation: '2021-02-21',
    dateDepart: '2021-02-21',
    heureArrivee: '03:00',
    heureDepart: '06:45',   
    validationReservation:  true ,
    vehiculeId:1,
    placeId:3,
    userUsername:"marie",
  },
  {
    codeReservation: "2021-03-01T08:00:00.000Z",
    dateReservation: '2021-05-15',
    dateOccupation: '2021-05-23',
    dateDepart: '2021-05-23',
    heureArrivee: '10:00',
    heureDepart: '12:10',   
    validationReservation:  true,
    vehiculeId:2,
    placeId:2,
    userUsername:"manou",
  },
  {
    codeReservation: "2021-02-01T08:02:11.000Z",
    dateReservation: '2021-03-21',
    dateOccupation: '2021-03-23',
    dateDepart: '2021-03-24',
    heureArrivee: '17:00',
    heureDepart: '19:10',   
    validationReservation:  true ,
    vehiculeId:3,
    placeId:1,
    userUsername:"louis",
  },
  ]);
  //remplissage de la table location
  await Location.bulkCreate([
    {
    date_Debut: '2021-02-21',
    date_Fin: '2021-02-21',
    heure_Debut: '03:00',
    heure_Fin: '06:45',   
    validationLocation: true,
    vehiculeId:11,
    userUsername:"parfait",
    placeId:5,
  },
  {
    date_Debut: '2021-05-14',
    date_Fin: '2021-05-14',
    heure_Debut: '13:00',
    heure_Fin: '16:45',   
    validationLocation: true, 
    vehiculeId:12,
    userUsername:"rachel",
    placeId:4,
  },
  {
    date_Debut: '2021-05-11',
    date_Fin: '2021-05-11',
    heure_Debut: '20:00',
    heure_Fin: '22:10',   
    validationLocation: false, 
    vehiculeId:13,
    userUsername:"romuald",
    placeId:3,
  },
  {
    date_Debut: '2021-01-11',
    date_Fin: '2021-01-12',
    heure_Debut: '23:00',
    heure_Fin: '05:10',   
    validationLocation: false, 
    vehiculeId:14,
    userUsername:"ron",
    placeId:2,
  },
  {
    date_Debut: '2021-02-27',
    date_Fin: '2021-02-27',
    heure_Debut: '12:00',
    heure_Fin: '12:30',   
    validationLocation: true, 
    vehiculeId:15,
    userUsername:"manou",
    placeId:1,
  },
  ]);
})();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   